### ISSUE TITLE
Support for UITableView

### ISSUE THREAD

**Issue by anirudhamahale** [noursandid/SundeedSpotlight#1]
How can I highlight the UIButton from UITableViewCell?

**Comment by noursandid** [comment]
Hi @anirudhamahale,

You need to make sure that the cell is displayed before showing the spotlight,
So in the below example I set some kind of a delay so the tableView would be done displaying all the needed cells



    DispatchQueue.main.asyncAfter(deadline: .now()+0.1) {
        if let cell = self.tableView.cellForRow(at: IndexPath(row: 0, section: 0)) {
            self.sundeedWalkthrough
                .addView(cell.button,
                                 withInfo: "1")
                .show()
        }
    }
